show generated number in popup message
pluginsGLPI/geninventorynumber pull request #85
Opened 2024-03-28 09:06 UTC by ciberfred

Help to know what is the number generated without goes back to inventory list page of the object.

2024-03-29 11:37 UTC, stonebuzz requested changes

2024-03-29 11:37 UTC, stonebuzz commented on inc/generation.class.php
> +               Session::addMessageAfterRedirect(__('An inventory number have been generated', 'geninventorynumber') . " " . $item->input['otherserial'], true);
```suggestion
               Session::addMessageAfterRedirect(sprintf(__('An inventory number have been generated (%1$s)', 'geninventorynumber'), $item->input['otherserial']), true);
```

2024-05-17 06:17 UTC, Rom1-B approved these changes

2024-05-17 06:23 UTC, stonebuzz approved these changes

2024-05-17 06:26 UTC, merged